# Generated by Django 4.0.8 on 2022-12-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VariantMarker',
            fields=[
                ('markerID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('locus', models.CharField(max_length=200)),
                ('alleles', models.CharField(max_length=200)),
                ('annotation', models.TextField()),
            ],
        ),
    ]
