# Generated by Django 4.0.8 on 2022-12-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0001_initial'),
        ('variantmarker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantmarker',
            name='geneID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gene.gene'),
        ),
    ]
