version: "3.9"
services:
  web:
    build: .
    command: python /Project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Project
    ports:
      - 8000:8000
    depends_on:
      - db
    # environment:
    #   - "DJANGO_SECRET_KEY=django-insecure-h9vxd-m=rqgboz)3*4vv^u+8sl$$kw%5ppr^f+ds$$*l)=@35pmq" 
  db:
    image: postgres:14
    volumes:
      - postgres_data:/Data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: