# Generated by Django 4.0.8 on 2022-12-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variantmarker', '0002_variantmarker_geneid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenebassVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_cases', models.FloatField()),
                ('n_controls', models.FloatField()),
                ('heritability', models.FloatField()),
                ('trait_type', models.CharField(max_length=200)),
                ('phenocode', models.CharField(max_length=200)),
                ('pheno_sex', models.CharField(max_length=200)),
                ('coding', models.CharField(max_length=200)),
                ('n_cases_defined', models.FloatField()),
                ('n_cases_both_sexes', models.FloatField()),
                ('n_cases_females', models.FloatField()),
                ('n_cases_males', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('AC', models.FloatField()),
                ('AF', models.FloatField()),
                ('BETA', models.FloatField()),
                ('SE', models.FloatField()),
                ('AF_Cases', models.FloatField()),
                ('AF_Controls', models.FloatField()),
                ('Pvalue', models.FloatField()),
                ('AC_calstat', models.FloatField()),
                ('AF_calstat', models.FloatField()),
                ('markerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variantmarker.variantmarker')),
            ],
        ),
    ]
