# Generated by Django 4.0.8 on 2022-12-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbvariant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genebassvariant',
            name='category',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='genebassvariant',
            name='coding',
            field=models.TextField(default='None'),
        ),
    ]
