# Generated by Django 4.0.8 on 2023-02-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('drugcategory', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category_detail', models.TextField(default='None')),
            ],
            options={
                'db_table': 'drugcategory',
            },
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('drugclass', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('class_detail', models.TextField(default='None')),
            ],
            options={
                'db_table': 'drugclass',
            },
        ),
        migrations.CreateModel(
            name='DrugGroup',
            fields=[
                ('druggroup', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('group_detail', models.TextField(default='None')),
            ],
            options={
                'db_table': 'druggroup',
            },
        ),
        migrations.CreateModel(
            name='DrugName',
            fields=[
                ('drugname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_detail', models.TextField(default='None')),
            ],
            options={
                'db_table': 'drugname',
            },
        ),
        migrations.CreateModel(
            name='DrugParent',
            fields=[
                ('drugparent', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('parent_detail', models.TextField(default='None')),
            ],
            options={
                'db_table': 'drugparent',
            },
        ),
        migrations.CreateModel(
            name='DrugPubChemCompound',
            fields=[
                ('compound', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('compound_detail', models.TextField(default='None')),
            ],
            options={
                'db_table': 'drugpubchemcompound',
            },
        ),
        migrations.CreateModel(
            name='DrugSubclass',
            fields=[
                ('drugsubclass', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subclass_detail', models.TextField(default='None')),
            ],
            options={
                'db_table': 'drugsubclass',
            },
        ),
        migrations.CreateModel(
            name='DrugSuperclass',
            fields=[
                ('drugsuperclass', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('superclass_detail', models.TextField(default='None')),
            ],
            options={
                'db_table': 'drugsuperclass',
            },
        ),
        migrations.CreateModel(
            name='DrugType',
            fields=[
                ('drugtype', models.IntegerField(primary_key=True, serialize=False)),
                ('type_detail', models.CharField(default='None', max_length=20)),
            ],
            options={
                'db_table': 'drugtype',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_bankID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('aliases', models.TextField()),
                ('indication', models.TextField()),
                ('pharmacodynamics', models.TextField()),
                ('moa', models.TextField()),
                ('absorption', models.TextField()),
                ('toxicity', models.TextField()),
                ('halflife', models.TextField()),
                ('distribution_volume', models.TextField()),
                ('protein_binding', models.TextField()),
                ('dosages', models.TextField()),
                ('properties', models.TextField()),
                ('atc_codes', models.TextField(default='None')),
                ('atc_code_detail', models.TextField(default='None')),
                ('chEMBL', models.CharField(default='None', max_length=250)),
                ('pubChemSubstance', models.TextField(default='None')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drugcategory')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drugclass')),
                ('direct_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drugparent')),
                ('drugtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drugtype')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.druggroup')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drugname')),
                ('pubChemCompound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drugpubchemcompound')),
                ('subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drugsubclass')),
                ('superclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drugsuperclass')),
            ],
            options={
                'db_table': 'drug',
            },
        ),
    ]
