# Generated by Django 4.0.8 on 2022-12-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    # print("printing from protein 0001_initial")
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('uniprot_ID', models.CharField(
                    max_length=50, primary_key=True, serialize=False)),
                ('genename', models.TextField()),
                ('geneID', models.CharField(max_length=50)),
                ('entry_name', models.TextField()),
                ('protein_name', models.TextField()),
            ],
        ),
    ]
