# Generated by Django 4.0.8 on 2022-12-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='custome_field',
            field=models.TextField(default='Note'),
            preserve_default=False,
        ),
    ]
