# Generated by Django 4.0.8 on 2023-05-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0006_protein_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='af_pdb',
            field=models.TextField(null=True),
        ),
    ]
