# Generated by Django 4.0.8 on 2023-08-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0007_protein_af_pdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='Protein_class',
            field=models.TextField(null=True),
        ),
    ]
