# Generated by Django 4.0.8 on 2022-12-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drug', '0001_initial'),
        ('protein', '0002_protein_custome_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('interaction_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('actions', models.TextField()),
                ('known_action', models.TextField()),
                ('interaction_type', models.CharField(max_length=100)),
                ('atc_codes', models.TextField()),
                ('pubmed_ids', models.TextField()),
                ('ChEMBL', models.TextField()),
                ('drug_bankID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drug')),
                ('uniprot_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
        ),
    ]
