# Generated by Django 4.0.8 on 2023-02-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='ChEMBL',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='atc_codes',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='pubmed_ids',
        ),
    ]
