# Generated by Django 4.0.8 on 2023-02-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_remove_interaction_chembl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='pubmed_ids',
            field=models.TextField(default='None'),
        ),
    ]
