# Generated by Django 4.0.8 on 2023-09-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0002_gene_primary_transcript'),
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genebassvariant',
            name='geneID',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='gene.gene'),
        ),
    ]
