# Generated by Django 4.0.8 on 2023-09-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0002_genebassvariant_geneid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genebassvariant',
            old_name='geneID',
            new_name='genename',
        ),
    ]
