# Generated by Django 4.0.8 on 2023-02-19 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gene', '0004_remove_gene_inv_normalized_remove_gene_saige_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('VariantMarker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Gene_ID', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='gene.gene')),
            ],
        ),
        migrations.CreateModel(
            name='VariantPhenocode',
            fields=[
                ('phenocode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pheno_sex', models.CharField(default='None', max_length=100)),
                ('description', models.TextField(null=True)),
                ('description_more', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VepVariant',
            fields=[
                ('vep_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Transcript_ID', models.CharField(max_length=20)),
                ('Consequence', models.CharField(max_length=255)),
                ('cDNA_position', models.CharField(max_length=50)),
                ('CDS_position', models.CharField(max_length=50)),
                ('Protein_position', models.CharField(max_length=50)),
                ('Amino_acids', models.CharField(max_length=20)),
                ('Codons', models.CharField(max_length=80)),
                ('Impact', models.CharField(max_length=50)),
                ('Strand', models.IntegerField()),
                ('BayesDel_addAF_rankscore', models.FloatField()),
                ('BayesDel_noAF_rankscore', models.FloatField()),
                ('CADD_raw_rankscore', models.FloatField()),
                ('ClinPred_rankscore', models.FloatField()),
                ('DANN_rankscore', models.FloatField()),
                ('DEOGEN2_rankscore', models.FloatField()),
                ('Eigen_PC_raw_coding_rankscore', models.FloatField()),
                ('Eigen_raw_coding_rankscore', models.FloatField()),
                ('FATHMM_converted_rankscore', models.FloatField()),
                ('GERP_RS_rankscore', models.FloatField()),
                ('GM12878_fitCons_rankscore', models.FloatField()),
                ('GenoCanyon_rankscore', models.FloatField()),
                ('H1_hESC_fitCons_rankscore', models.FloatField()),
                ('HUVEC_fitCons_rankscore', models.FloatField()),
                ('LIST_S2_rankscore', models.FloatField()),
                ('LRT_converted_rankscore', models.FloatField()),
                ('M_CAP_rankscore', models.FloatField()),
                ('MPC_rankscore', models.FloatField()),
                ('MVP_rankscore', models.FloatField()),
                ('MetaLR_rankscore', models.FloatField()),
                ('MetaRNN_rankscore', models.FloatField()),
                ('MetaSVM_rankscore', models.FloatField()),
                ('MutPred_rankscore', models.FloatField()),
                ('MutationAssessor_rankscore', models.FloatField()),
                ('MutationTaster_converted_rankscore', models.FloatField()),
                ('PROVEAN_converted_rankscore', models.FloatField()),
                ('Polyphen2_HDIV_rankscore', models.FloatField()),
                ('Polyphen2_HVAR_rankscore', models.FloatField()),
                ('PrimateAI_rankscore', models.FloatField()),
                ('REVEL_rankscore', models.FloatField()),
                ('SIFT4G_converted_rankscore', models.FloatField()),
                ('SIFT_converted_rankscore', models.FloatField()),
                ('SiPhy_29way_logOdds_rankscore', models.FloatField()),
                ('VEST4_rankscore', models.FloatField()),
                ('bStatistic_converted_rankscore', models.FloatField()),
                ('Fathmm_MKL_coding_rankscore', models.FloatField()),
                ('Fathmm_XF_coding_rankscore', models.FloatField()),
                ('Integrated_fitCons_rankscore', models.FloatField()),
                ('PhastCons30way_mammalian_rankscore', models.FloatField()),
                ('PhyloP30way_mammalian_rankscore', models.FloatField()),
                ('LINSIGHT_rankscore', models.FloatField()),
                ('Variant_marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.variant')),
            ],
        ),
        migrations.CreateModel(
            name='GenebassVariant',
            fields=[
                ('gb_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('n_cases', models.FloatField()),
                ('n_controls', models.FloatField()),
                ('heritability', models.FloatField()),
                ('trait_type', models.CharField(max_length=200)),
                ('phenocode', models.CharField(max_length=200)),
                ('pheno_sex', models.CharField(max_length=200)),
                ('coding', models.TextField(default='None')),
                ('n_cases_defined', models.FloatField()),
                ('n_cases_both_sexes', models.FloatField()),
                ('n_cases_females', models.FloatField()),
                ('n_cases_males', models.FloatField()),
                ('category', models.TextField(default='None')),
                ('AC', models.FloatField()),
                ('AF', models.FloatField()),
                ('BETA', models.FloatField()),
                ('SE', models.FloatField()),
                ('AF_Cases', models.FloatField()),
                ('AF_Controls', models.FloatField()),
                ('Pvalue', models.FloatField()),
                ('AC_calstat', models.FloatField()),
                ('AF_calstat', models.FloatField()),
                ('Phenocode', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='variant.variantphenocode')),
                ('markerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.variant')),
            ],
        ),
    ]
