# Generated by Django 4.0.8 on 2022-12-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gene', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenebassVariant',
            fields=[
                ('genebass_variant_id', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('locus', models.CharField(max_length=200)),
                ('alleles', models.CharField(max_length=200)),
                ('markerID', models.CharField(max_length=200)),
                ('annotation', models.CharField(max_length=200)),
                ('n_cases', models.FloatField()),
                ('n_controls', models.FloatField()),
                ('heritability', models.FloatField()),
                ('trait_type', models.CharField(max_length=200)),
                ('phenocode', models.CharField(max_length=200)),
                ('pheno_sex', models.CharField(max_length=200)),
                ('coding', models.CharField(max_length=200)),
                ('n_cases_defined', models.FloatField()),
                ('n_cases_both_sexes', models.FloatField()),
                ('n_cases_females', models.FloatField()),
                ('n_cases_males', models.FloatField()),
                ('description', models.TextField()),
                ('description_more', models.TextField()),
                ('coding_description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('AC', models.FloatField()),
                ('AF', models.FloatField()),
                ('BETA', models.FloatField()),
                ('SE', models.FloatField()),
                ('AF_Cases', models.FloatField()),
                ('AF_Controls', models.FloatField()),
                ('Pvalue', models.FloatField()),
                ('AC_calstat', models.FloatField()),
                ('AF_calstat', models.FloatField()),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.gene')),
            ],
        ),
    ]
