# Generated by Django 4.0.8 on 2023-02-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vepvariant',
            name='Amino_acids',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vepvariant',
            name='CDS_position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vepvariant',
            name='Codons',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vepvariant',
            name='Protein_position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vepvariant',
            name='Transcript_ID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vepvariant',
            name='cDNA_position',
            field=models.CharField(max_length=255),
        ),
    ]
