# Generated by Django 4.0.8 on 2023-09-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0003_rename_geneid_genebassvariant_genename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genebassvariant',
            old_name='genename',
            new_name='gene_id',
        ),
    ]
