# Generated by Django 4.0.8 on 2023-02-19 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0003_delete_genebassvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenebassVariant',
            fields=[
                ('gb_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('n_cases', models.FloatField()),
                ('n_controls', models.FloatField()),
                ('n_cases_defined', models.FloatField()),
                ('n_cases_both_sexes', models.FloatField()),
                ('n_cases_females', models.FloatField()),
                ('n_cases_males', models.FloatField()),
                ('category', models.CharField(max_length=10)),
                ('AC', models.FloatField()),
                ('AF', models.FloatField()),
                ('BETA', models.FloatField()),
                ('SE', models.FloatField()),
                ('AF_Cases', models.FloatField()),
                ('AF_Controls', models.FloatField()),
                ('Pvalue', models.FloatField()),
                ('AC_calstat', models.FloatField()),
                ('AF_calstat', models.FloatField()),
                ('markerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.variant')),
                ('phenocode', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='variant.variantphenocode')),
            ],
        ),
    ]
