# Generated by Django 4.0.8 on 2023-02-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0004_genebassvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genebassvariant',
            name='AC_calstat',
        ),
        migrations.RemoveField(
            model_name='genebassvariant',
            name='AF_calstat',
        ),
    ]
