# Generated by Django 4.0.8 on 2022-12-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_bankID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('drugtype', models.IntegerField()),
                ('name', models.CharField(max_length=225)),
                ('groups', models.CharField(default='None', max_length=50)),
                ('categories', models.CharField(default='None', max_length=50)),
                ('description', models.TextField()),
                ('aliases', models.TextField()),
                ('kingdom', models.CharField(default='None', max_length=50)),
                ('superclass', models.CharField(default='None', max_length=50)),
                ('classname', models.CharField(default='None', max_length=50)),
                ('subclass', models.CharField(default='None', max_length=50)),
                ('direct_parent', models.CharField(default='None', max_length=50)),
                ('indication', models.TextField()),
                ('pharmacodynamics', models.TextField()),
                ('moa', models.TextField()),
                ('absorption', models.TextField()),
                ('toxicity', models.TextField()),
                ('halflife', models.TextField()),
                ('distribution_volume', models.TextField()),
                ('protein_binding', models.TextField()),
                ('dosages', models.TextField()),
                ('properties', models.TextField()),
            ],
        ),
    ]
