# Generated by Django 4.0.8 on 2023-02-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drug',
            table=None,
        ),
    ]
