# Generated by Django 4.0.8 on 2023-02-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='pubmed_ids',
        ),
    ]
