# Generated by Django 4.0.8 on 2023-09-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='primary_transcript',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
