# Generated by Django 4.0.8 on 2022-12-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VariantPhenocode',
            fields=[
                ('phenocode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('description_more', models.TextField()),
            ],
        ),
    ]
