# Generated by Django 4.0.8 on 2022-12-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantphenocode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantphenocode',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='variantphenocode',
            name='description_more',
            field=models.TextField(null=True),
        ),
    ]
