# Generated by Django 4.0.8 on 2022-12-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('genename', models.CharField(max_length=50)),
                ('saige_version', models.CharField(max_length=50)),
                ('inv_normalized', models.CharField(max_length=50)),
            ],
        ),
    ]
