# Generated by Django 4.0.8 on 2023-02-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0002_editors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editors',
        ),
    ]
