# Generated by Django 4.0.8 on 2022-12-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_protein_custome_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='custome_field',
        ),
    ]
