# Generated by Django 4.0.8 on 2023-08-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='Clinical_status',
            field=models.IntegerField(null=True),
        ),
    ]
