# Generated by Django 4.0.8 on 2022-12-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vep', '0003_vep_deogen2_score_std_vep_fathmm_score_std_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vep',
            name='LRT_pred',
            field=models.CharField(max_length=10),
        ),
    ]
