# Generated by Django 4.0.8 on 2022-12-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vep', '0004_alter_vep_lrt_pred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vep',
            name='MutationTaster_AAE',
        ),
    ]
