# Generated by Django 4.0.8 on 2022-12-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vep', '0005_remove_vep_mutationtaster_aae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vep',
            name='MutationTaster_pred',
            field=models.CharField(max_length=10),
        ),
    ]
