# Generated by Django 4.0.8 on 2022-12-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vep', '0006_alter_vep_mutationtaster_pred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vep',
            name='CDS_position',
            field=models.CharField(max_length=50),
        ),
    ]
