# Generated by Django 4.0.8 on 2022-12-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vep', '0009_alter_vep_protein_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vep',
            name='markerID',
        ),
    ]
