# Generated by Django 4.0.8 on 2022-12-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variantmarker', '0002_variantmarker_geneid'),
        ('vep', '0010_remove_vep_markerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vep',
            name='markerID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='variantmarker.variantmarker'),
        ),
    ]
